### ISSUE TITLE
Code Error | not running

### ISSUE THREAD

**Issue by shubhamgautam13** [the-Infected-Drake/TIDoS-Framework#10]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 15, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google

**Comment by R00T88** [comment]
Hello got the same error on Kali linux
Can you fix it?

**Comment by the-Infected-Drake** [comment]
I will be working on the code rightaway, thank you for your responses.
Something is causing the problem. Please be patient. : )
- @_tID

**Comment by easyguyme** [comment]
I am experiencing the same issue
