### ISSUE TITLE
clickjack error 

### ISSUE THREAD

**Issue by shubhamdt** [the-Infected-Drake/TIDoS-Framework#11]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 409, in <module>
    tidosmain()
  File "/opt/tidos/tidos.py", line 282, in tidosmain
    clickjack()
  File "/opt/tidos/clickjack.py", line 56, in clickjack
    print (""+R+"                               Target set :> %s" % (site))
NameError: global name 'site' is not defined

**Comment by the-Infected-Drake** [comment]
I am working on version 2.1.0 of this and will be updating it within a week. Please keep patience till then. 
:)

> @_tID
