### ISSUE TITLE
ImportError: No module named google

### ISSUE THREAD

**Issue by gitxmax** [the-Infected-Drake/TIDoS-Framework#8]
Reinstall doesn't help..

Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from google)
  [!] SetUP Successfull ! Execute 'tidos' now to launch the tool [!]
  [+] Also note that the next time, you want to run this tool, just simply execute 'tidos' in terminal.

root@kali:~/TIDoS-Framework# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google

**Comment by the-Infected-Drake** [comment]
You can refer to this issue [here](https://github.com/the-Infected-Drake/TIDoS-Framework/issues/4). If this doesn't help, let me know.

**Comment by trollmad3** [comment]
@gitxmax Type into console `apt-get install google`

**Comment by gregkrsak** [comment]
I'm getting the same thing:

```
[!] SetUP Successfull ! Execute 'tidos' now to launch the tool [!]
  [+] Also note that the next time, you want to run this tool, just simply execute 'tidos' in terminal.
greg@swany-laptop:~/h/TIDoS-Framework$ tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 15, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google
greg@swany-laptop:~/h/TIDoS-Framework$ uname -a
Linux swany-laptop 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
greg@swany-laptop:~/h/TIDoS-Framework$ sudo apt-get install google
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package google
greg@swany-laptop:~/h/TIDoS-Framework$ sudo pip install google
Requirement already satisfied (use --upgrade to upgrade): google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google)
```
