### ISSUE TITLE
import google

### ISSUE THREAD

**Issue by pathibulaire64** [the-Infected-Drake/TIDoS-Framework#9]
Hy,
I've the same error, i follow yours instructions but the result is the same.
i work on 4.13.0-kali1-686- usb persistence.
All installation is ok
python-pip is already the newest version (9.0.1-2).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 1166 non mis à jour.
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages .....
...
Requirement already satisfied: scapy in /usr/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google)

And when i print "tidos":

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google

The first issues is line 3 import search
after your fix is in line 2 import google
I don't understand, can you help me?
Thanks

**Comment by pathibulaire64** [comment]
Great, I fix it, so i search on my disk "google.py" ,i find it on"usr/lib/python2.7/dist-packages/demo/"
and i copied it in "usr/lib/python2.7/dist-packages/";
And all work fine!!!
Thanks
